[[redirects]]
  from = "/auth/google"
  to = "https://gift-server-hena.onrender.com/auth/google"
  status = 200
  force = true
 
[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200
  force = true
  

