[[redirects]]
  from = "/auth/google"
  to = "https://gift-server-hena.onrender.com/auth/google"
  status = 200
  force = true
  

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
