[[redirects]]
  from = "/auth/google"
  to = "https://xs-xegm.onrender.com/auth/google"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"